FROM node:16

WORKDIR /app

# 复制package.json和package-lock.json
COPY ./frontend/package*.json ./

# 安装项目依赖
RUN npm install

# 复制所有源代码
COPY ./frontend/ ./

# 暴露5173端口
EXPOSE 5173

# 启动服务
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"] 