version: '3.9'

services:
  model-service:
    build:
      context: ..
      dockerfile: model_service/Dockerfile
    container_name: model-service
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ../.env:/app/.env
    environment:
      - ENV_FILE=/app/.env
      - REDIS_HOST=redis  # 假设redis已经启动，使用默认的host名
      - REDIS_PORT=6379
      - REDIS_DB=0
    networks:
      - model-network
      - redis-network  # 连接到redis所在的网络

networks:
  model-network:
    driver: bridge
  redis-network:
    external: true  # 假设redis网络已经存在，这里只是引用它 